import { useMemo, useState } from "react";
import type { AuthConfig, BlueprintV1, EntityConfig, EntityFieldConfig, MenuItem, ResourceConfig, RoleConfig } from "../contracts/blueprint";
import type { ProjectSession } from "../contracts/workspace";

const uuid = () => crypto.randomUUID();
type Commit = (update: (blueprint: BlueprintV1) => BlueprintV1) => void;
const CRUD_ACTIONS = ["read", "create", "update", "delete"];

function synchronizeEntityMenuResources(blueprint: BlueprintV1) {
  const resources = structuredClone(blueprint.resources);
  const roles = structuredClone(blueprint.roles);
  const menus = structuredClone(blueprint.menus);
  for (const [key, entity] of Object.entries(blueprint.entities)) {
    const resource = resources[key] ?? { id: uuid(), key, resourceType: "entity", actions: [...CRUD_ACTIONS] };
    resources[key] = resource;
    for (const [roleKey, role] of Object.entries(roles)) {
      if (role.key !== "superadmin") continue;
      const granted = new Set(role.permissions[resource.id] ?? []);
      CRUD_ACTIONS.forEach((action) => granted.add(action));
      roles[roleKey] = { ...role, permissions: { ...role.permissions, [resource.id]: [...granted] } };
    }
    if (!menus.some((menu) => menu.resourceId === resource.id)) {
      menus.push({ id: uuid(), label: entity.label || key, resourceId: resource.id, order: menus.length });
    }
  }
  return { resources, roles, menus };
}

export function EntityEditor({ session, onCommit }: { session: ProjectSession; onCommit: Commit }) {
  const original = session.blueprint.entities;
  const [draft, setDraft] = useState<Record<string, EntityConfig>>(() => structuredClone(original));
  const [selected, setSelected] = useState(Object.keys(draft)[0] ?? "");
  const [selectedField, setSelectedField] = useState("");
  const tables = session.blueprint.databases.main.tables;
  const current = draft[selected];
  const table = tables.find((item) => item.id === current?.tableId);
  const dirty = JSON.stringify(draft) !== JSON.stringify(original);
  const addEntity = (tableId: string) => {
    const source = tables.find((item) => item.id === tableId); if (!source) return;
    const key = source.name;
    const entity: EntityConfig = { id: uuid(), label: source.name.replaceAll("_", " "), databaseId: session.blueprint.databases.main.id, tableId: source.id, fields: Object.fromEntries(source.columns.map((column) => [column.name, { id: uuid(), columnId: column.id, control: column.canonicalType === "boolean" ? "switch" : column.canonicalType === "date" || column.canonicalType === "dateTime" ? "date" : "text", showInList: true, showInView: true, showInForm: !column.primaryKey, required: !column.nullable, validation: [], options: [] }])) };
    setDraft((value) => ({ ...value, [key]: entity })); setSelected(key); setSelectedField(Object.keys(entity.fields)[0] ?? "");
  };
  const changeField = (key: string, patch: Partial<EntityConfig["fields"][string]>) => setDraft((value) => ({ ...value, [selected]: { ...value[selected], fields: { ...value[selected].fields, [key]: { ...value[selected].fields[key], ...patch } } } }));
  return <ConfigShell eyebrow="ENTITY / FORM CONFIG" title="Entity presentation" description="Bind canonical columns to list, detail, and form behavior." dirty={dirty} onSave={() => onCommit((blueprint) => { const next = { ...blueprint, entities: draft }; return { ...next, ...synchronizeEntityMenuResources(next) }; })} onDiscard={() => { setDraft(structuredClone(original)); setSelected(Object.keys(original)[0] ?? ""); }}>
    <div className="config-split"><aside className="config-list"><select value="" onChange={(event) => addEntity(event.target.value)}><option value="">+ Add entity from table</option>{tables.filter((item) => !Object.values(draft).some((entity) => entity.tableId === item.id)).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select>{Object.entries(draft).map(([key, entity]) => <button className={key === selected ? "active" : ""} onClick={() => { setSelected(key); setSelectedField(Object.keys(entity.fields)[0] ?? ""); }} key={entity.id}><b>{entity.label ?? key}</b><span>{key}</span></button>)}</aside><section className="config-detail">{current && table ? <><label>Entity label<input value={current.label ?? ""} onChange={(event) => setDraft((value) => ({ ...value, [selected]: { ...current, label: event.target.value } }))} /></label><div className="field-config-header"><span>Field</span><span>Control</span><span>List</span><span>View</span><span>Form</span><span>Required</span></div>{Object.entries(current.fields).map(([key, field]) => { const column = table.columns.find((item) => item.id === field.columnId); return <div className={key === selectedField ? "field-config-row selected" : "field-config-row"} key={field.id}><button className="field-name" onClick={() => setSelectedField(key)}><b>{key}</b><small>{column?.canonicalType}</small></button><select value={field.control} onChange={(event) => changeField(key, { control: event.target.value })}>{["text", "textarea", "number", "switch", "date", "select", "radio", "hidden"].map((value) => <option key={value}>{value}</option>)}</select>{(["showInList", "showInView", "showInForm", "required"] as const).map((property) => <input key={property} type="checkbox" checked={field[property]} onChange={(event) => changeField(key, { [property]: event.target.checked })} />)}</div>})}{selectedField && current.fields[selectedField] && <FieldAdvanced field={current.fields[selectedField]} entities={draft} onChange={(patch) => changeField(selectedField, patch)} />}<button className="secondary danger" onClick={() => { const next = { ...draft }; delete next[selected]; setDraft(next); setSelected(Object.keys(next)[0] ?? ""); setSelectedField(""); }}>Remove entity config</button></> : <EmptyConfig text="Add an entity from an introspected table." />}</section></div>
  </ConfigShell>;
}

export function PermissionEditor({ session, onCommit }: { session: ProjectSession; onCommit: Commit }) {
  const [initialAccess] = useState(() => synchronizeEntityMenuResources(session.blueprint));
  const [resources, setResources] = useState<Record<string, ResourceConfig>>(() => initialAccess.resources);
  const [roles, setRoles] = useState<Record<string, RoleConfig>>(() => initialAccess.roles);
  const [menus, setMenus] = useState<MenuItem[]>(() => initialAccess.menus);
  const [entityKey, setEntityKey] = useState("");
  const [roleKey, setRoleKey] = useState("");
  const [resourceKey, setResourceKey] = useState("");
  const [actionKey, setActionKey] = useState("");
  const [actionResourceId, setActionResourceId] = useState("");
  const [selectedRoleKey, setSelectedRoleKey] = useState(() => Object.keys(session.blueprint.roles)[0] ?? "");
  const [selectedResourceId, setSelectedResourceId] = useState(() => Object.values(initialAccess.resources)[0]?.id ?? "");
  const currentSnapshot = JSON.stringify([resources, roles, menus]);
  const [appliedSnapshot, setAppliedSnapshot] = useState(() => JSON.stringify([initialAccess.resources, initialAccess.roles, initialAccess.menus]));
  const dirty = currentSnapshot !== appliedSnapshot;
  const entities = Object.entries(session.blueprint.entities).map(([key, entity]) => ({ key, label: entity.label || key }));
  const resourceList = Object.values(resources);
  const roleList = Object.entries(roles);
  const activeRole = roles[selectedRoleKey];
  const activeResource = resourceList.find((resource) => resource.id === selectedResourceId);
  const menuResourceIds = new Set(menus.map((menu) => menu.resourceId).filter((id): id is string => Boolean(id)));
  const menuEntities = entities.filter((entity) => !menuResourceIds.has(resources[entity.key]?.id ?? ""));
  const safeKey = (value: string) => /^[A-Za-z][A-Za-z0-9_-]*$/.test(value);
  const addResource = (key: string) => {
    if (!safeKey(key) || resources[key]) return;
    const id = uuid();
    const actions = ["read", "create", "update", "delete"];
    setResources((value) => ({ ...value, [key]: { id, key, resourceType: "entity", actions } }));
    setRoles((value) => Object.fromEntries(Object.entries(value).map(([roleKeyValue, role]) => [roleKeyValue, role.key === "superadmin" ? { ...role, permissions: { ...role.permissions, [id]: actions } } : role])));
    setActionResourceId(id); setSelectedResourceId(id);
  };
  const addEntityMenu = () => {
    const key = entityKey || menuEntities[0]?.key;
    const entity = entities.find((item) => item.key === key);
    if (!key || !entity) return;
    const resourceId = resources[key]?.id ?? uuid();
    const actions = ["read", "create", "update", "delete"];
    if (!resources[key]) {
      setResources((value) => ({ ...value, [key]: { id: resourceId, key, resourceType: "entity", actions } }));
      setRoles((value) => Object.fromEntries(Object.entries(value).map(([roleKeyValue, role]) => [roleKeyValue, role.key === "superadmin" ? { ...role, permissions: { ...role.permissions, [resourceId]: actions } } : role])));
    }
    setMenus((value) => value.some((menu) => menu.resourceId === resourceId) ? value : [...value, { id: uuid(), label: entity.label, resourceId, order: value.length }]);
    setActionResourceId(resourceId); setSelectedResourceId(resourceId); setEntityKey("");
  };
  const addManualResource = () => { addResource(resourceKey.trim()); setResourceKey(""); };
  const addRole = () => { const key = roleKey.trim(); if (!safeKey(key) || roles[key]) return; setRoles((value) => ({ ...value, [key]: { id: uuid(), key, label: key, permissions: {} } })); setSelectedRoleKey(key); setRoleKey(""); };
  const toggle = (role: string, resource: ResourceConfig, action: string) => setRoles((value) => { const current = value[role].permissions[resource.id] ?? []; const actions = current.includes(action) ? current.filter((item) => item !== action) : [...current, action]; return { ...value, [role]: { ...value[role], permissions: { ...value[role].permissions, [resource.id]: actions } } }; });
  const toggleAll = () => { if (!activeRole || !activeResource) return; setRoles((value) => { const current = value[selectedRoleKey].permissions[activeResource.id] ?? []; const complete = activeResource.actions.every((action) => current.includes(action)); return { ...value, [selectedRoleKey]: { ...value[selectedRoleKey], permissions: { ...value[selectedRoleKey].permissions, [activeResource.id]: complete ? [] : [...activeResource.actions] } } }; }); };
  const addAction = () => { const action = actionKey.trim(); if (!safeKey(action) || !actionResourceId) return; setResources((value) => Object.fromEntries(Object.entries(value).map(([key, resource]) => [key, resource.id === actionResourceId && !resource.actions.includes(action) ? { ...resource, actions: [...resource.actions, action] } : resource]))); setActionKey(""); };
  const removeAction = (resourceId: string, action: string) => { setResources((value) => Object.fromEntries(Object.entries(value).map(([key, resource]) => [key, resource.id === resourceId ? { ...resource, actions: resource.actions.filter((item) => item !== action) } : resource]))); setRoles((value) => Object.fromEntries(Object.entries(value).map(([key, role]) => [key, { ...role, permissions: { ...role.permissions, [resourceId]: (role.permissions[resourceId] ?? []).filter((item) => item !== action) } }]))); };
  const removeResource = (key: string, resourceId: string) => { setResources((value) => { const next = { ...value }; delete next[key]; return next; }); setRoles((value) => Object.fromEntries(Object.entries(value).map(([roleKeyValue, role]) => { const permissions = { ...role.permissions }; delete permissions[resourceId]; return [roleKeyValue, { ...role, permissions }]; }))); setMenus((value) => value.map((menu) => menu.resourceId === resourceId ? { ...menu, resourceId: undefined } : menu)); if (selectedResourceId === resourceId) setSelectedResourceId(""); if (actionResourceId === resourceId) setActionResourceId(""); };
  const updateMenu = (index: number, patch: Partial<MenuItem>) => setMenus((value) => value.map((item, at) => at === index ? { ...item, ...patch } : item));
  const apply = () => { onCommit((blueprint) => ({ ...blueprint, resources, roles, menus })); setAppliedSnapshot(currentSnapshot); };
  const discard = () => { const next = synchronizeEntityMenuResources(session.blueprint); setResources(next.resources); setRoles(next.roles); setMenus(next.menus); setAppliedSnapshot(JSON.stringify([next.resources, next.roles, next.menus])); };
  return <ConfigShell eyebrow="ACCESS CONTROL" title="Set access by role" description="Every Entity menu is automatically available as a resource. Choose a role, then configure its actions." dirty={dirty} onSave={apply} onDiscard={discard}>
    <div className="permission-guided access-only"><section><span className="step-number">1</span><div><b>Choose a role</b><small>Roles are reused across every Entity menu resource.</small></div><select aria-label="Role to configure" value={selectedRoleKey} onChange={(event) => setSelectedRoleKey(event.target.value)}><option value="">Choose a role</option>{roleList.map(([key, role]) => <option value={key} key={role.id}>{role.label} ({key})</option>)}</select></section><section><span className="step-number">2</span><div><b>Choose a menu resource</b><small>All Entity menus are listed here automatically.</small></div><select aria-label="Grant resource" value={selectedResourceId} onChange={(event) => setSelectedResourceId(event.target.value)} disabled={!activeRole}><option value="">Choose a resource</option>{resourceList.map((resource) => <option value={resource.id} key={resource.id}>{resource.key}</option>)}</select>{activeResource && <button className="secondary" onClick={toggleAll}>{activeResource.actions.every((action) => (activeRole?.permissions[activeResource.id] ?? []).includes(action)) ? "Clear all" : "Grant all"}</button>}</section></div>
    <section className="permission-focus"><div className="panel-title"><span>{activeRole ? `Permissions for ${activeRole.label}` : "Choose a role first"}</span><small>{activeResource?.key ?? "no resource selected"}</small></div>{activeRole && activeResource ? <div className="permission-action-list">{activeResource.actions.map((action) => <label key={action} className={(activeRole.permissions[activeResource.id] ?? []).includes(action) ? "selected" : ""}><input type="checkbox" aria-label={`${activeRole.key} ${activeResource.key} ${action}`} checked={(activeRole.permissions[activeResource.id] ?? []).includes(action)} onChange={() => toggle(selectedRoleKey, activeResource, action)} /><span>{action}</span><small>{action === "read" ? "View records" : action === "create" ? "Add records" : action === "update" ? "Edit records" : action === "delete" ? "Delete records" : "Custom action"}</small></label>)}</div> : <div className="empty-state compact"><strong>Choose role and resource</strong><span>The available actions will appear here, instead of in a large matrix.</span></div>}</section>
    <details className="permission-advanced"><summary>Advanced options: custom resource, role, or action</summary><div className="permission-builders"><div className="inline-form"><input value={resourceKey} onChange={(event) => setResourceKey(event.target.value)} placeholder="resource key" /><button onClick={addManualResource}>Add resource</button></div><div className="inline-form"><input value={roleKey} onChange={(event) => setRoleKey(event.target.value)} placeholder="role key" /><button onClick={addRole}>Add role</button></div><div className="inline-form"><select aria-label="Action resource" value={actionResourceId} onChange={(event) => setActionResourceId(event.target.value)}><option value="">Resource</option>{resourceList.map((resource) => <option value={resource.id} key={resource.id}>{resource.key}</option>)}</select><input value={actionKey} onChange={(event) => setActionKey(event.target.value)} placeholder="custom action" /><button onClick={addAction}>Add action</button></div></div></details>
    <div className="permission-inventory"><section><div className="panel-title"><span>Resources</span><small>{resourceList.length}</small></div>{Object.entries(resources).map(([key, resource]) => <div className="inventory-row" key={resource.id}><b>{resource.key}</b><span>{resource.actions.map((action) => <button aria-label={`Remove ${resource.key} ${action} action`} onClick={() => removeAction(resource.id, action)} key={action}>{action} ×</button>)}</span><button className="danger" aria-label={`Remove resource ${resource.key}`} onClick={() => removeResource(key, resource.id)}>Remove</button></div>)}</section><section><div className="panel-title"><span>Roles</span><small>{roleList.length}</small></div>{roleList.map(([key, role]) => <div className="inventory-row" key={role.id}><input aria-label={`${role.key} role label`} value={role.label} onChange={(event) => setRoles((value) => ({ ...value, [key]: { ...role, label: event.target.value } }))} /><button className="danger" aria-label={`Remove role ${role.key}`} onClick={() => setRoles((value) => { const next = { ...value }; delete next[key]; return next; })}>Remove</button></div>)}</section></div>
    <section className="menu-config"><div className="panel-title"><span>Menu mapping</span><small>optional / not authorization</small></div><button className="secondary" onClick={() => { const resource = resourceList[0]; setMenus((value) => [...value, { id: uuid(), label: resource?.key ?? "Menu item", resourceId: resource?.id, order: value.length }]); }}>Add menu item</button>{menus.map((menu, index) => <div className="menu-row advanced" key={menu.id}><input aria-label={`Menu ${index + 1} label`} value={menu.label} onChange={(event) => updateMenu(index, { label: event.target.value })} /><select aria-label={`Menu ${index + 1} resource`} value={menu.resourceId ?? ""} onChange={(event) => updateMenu(index, { resourceId: event.target.value || undefined })}><option value="">No resource</option>{resourceList.map((resource) => <option value={resource.id} key={resource.id}>{resource.key}</option>)}</select><select aria-label={`Menu ${index + 1} parent`} value={menu.parentId ?? ""} onChange={(event) => updateMenu(index, { parentId: event.target.value || undefined })}><option value="">Top level</option>{menus.filter((candidate) => candidate.id !== menu.id).map((candidate) => <option value={candidate.id} key={candidate.id}>{candidate.label}</option>)}</select><input aria-label={`Menu ${index + 1} order`} type="number" value={menu.order} onChange={(event) => updateMenu(index, { order: Number(event.target.value) })} /><button className="danger" aria-label={`Remove menu ${index + 1}`} onClick={() => setMenus((value) => value.filter((_, at) => at !== index).map((item) => item.parentId === menu.id ? { ...item, parentId: undefined } : item))}>Remove</button></div>)}</section>
  </ConfigShell>;
}

function LegacyPermissionEditor({ session, onCommit }: { session: ProjectSession; onCommit: Commit }) {
  const [resources, setResources] = useState<Record<string, ResourceConfig>>(() => structuredClone(session.blueprint.resources));
  const [roles, setRoles] = useState<Record<string, RoleConfig>>(() => structuredClone(session.blueprint.roles));
  const [menus, setMenus] = useState<MenuItem[]>(() => structuredClone(session.blueprint.menus));
  const [resourceKey, setResourceKey] = useState("");
  const [roleKey, setRoleKey] = useState("");
  const [actionKey, setActionKey] = useState("");
  const [actionResourceId, setActionResourceId] = useState("");
  const [entityResourceKey, setEntityResourceKey] = useState("");
  const [selectedRoleKey, setSelectedRoleKey] = useState(() => Object.keys(session.blueprint.roles)[0] ?? "");
  const [grantResourceId, setGrantResourceId] = useState("");
  const original = JSON.stringify([session.blueprint.resources, session.blueprint.roles, session.blueprint.menus]);
  const dirty = JSON.stringify([resources, roles, menus]) !== original;
  const safeKey = (value: string) => /^[A-Za-z][A-Za-z0-9_-]*$/.test(value);
  const entities = Object.entries(session.blueprint.entities).map(([key, entity]) => ({ key, label: entity.label || key }));
  const resourceList = Object.values(resources);
  const availableEntityResources = entities.filter((entity) => !resources[entity.key]);
  const selectedRole = roles[selectedRoleKey];
  const grantResource = resourceList.find((resource) => resource.id === grantResourceId);
  const addResource = () => { const key = resourceKey.trim(); if (!safeKey(key) || resources[key]) return; const id = uuid(); setResources((value) => ({ ...value, [key]: { id, key, resourceType: "entity", actions: ["read", "create", "update", "delete"] } })); setActionResourceId((value) => value || id); setGrantResourceId((value) => value || id); setResourceKey(""); };
  const addEntityResource = () => { const key = entityResourceKey || availableEntityResources[0]?.key; if (!key || resources[key]) return; const id = uuid(); setResources((value) => ({ ...value, [key]: { id, key, resourceType: "entity", actions: ["read", "create", "update", "delete"] } })); setActionResourceId(id); setGrantResourceId(id); setEntityResourceKey(""); };
  const addRole = () => { const key = roleKey.trim(); if (!safeKey(key) || roles[key]) return; setRoles((value) => ({ ...value, [key]: { id: uuid(), key, label: key, permissions: {} } })); setSelectedRoleKey(key); setRoleKey(""); };
  const addAction = () => { const action = actionKey.trim(); if (!safeKey(action) || !actionResourceId) return; setResources((value) => Object.fromEntries(Object.entries(value).map(([key, resource]) => [key, resource.id === actionResourceId && !resource.actions.includes(action) ? { ...resource, actions: [...resource.actions, action] } : resource]))); setActionKey(""); };
  const toggle = (roleKeyValue: string, resource: ResourceConfig, action: string) => setRoles((value) => { const role = value[roleKeyValue]; const current = role.permissions[resource.id] ?? []; const actions = current.includes(action) ? current.filter((item) => item !== action) : [...current, action]; return { ...value, [roleKeyValue]: { ...role, permissions: { ...role.permissions, [resource.id]: actions } } }; });
  const toggleAll = (roleKeyValue: string, resource: ResourceConfig) => setRoles((value) => { const role = value[roleKeyValue]; const current = role.permissions[resource.id] ?? []; const complete = resource.actions.every((action) => current.includes(action)); return { ...value, [roleKeyValue]: { ...role, permissions: { ...role.permissions, [resource.id]: complete ? [] : [...resource.actions] } } }; });
  const removeAction = (resourceId: string, action: string) => { setResources((value) => Object.fromEntries(Object.entries(value).map(([key, resource]) => [key, resource.id === resourceId ? { ...resource, actions: resource.actions.filter((item) => item !== action) } : resource]))); setRoles((value) => Object.fromEntries(Object.entries(value).map(([key, role]) => [key, { ...role, permissions: { ...role.permissions, [resourceId]: (role.permissions[resourceId] ?? []).filter((item) => item !== action) } }] ))); };
  const removeResource = (key: string, resourceId: string) => { setResources((value) => { const next = { ...value }; delete next[key]; return next; }); setRoles((value) => Object.fromEntries(Object.entries(value).map(([roleKeyValue, role]) => { const permissions = { ...role.permissions }; delete permissions[resourceId]; return [roleKeyValue, { ...role, permissions }]; }))); setMenus((value) => value.map((menu) => menu.resourceId === resourceId ? { ...menu, resourceId: undefined } : menu)); if (actionResourceId === resourceId) setActionResourceId(""); };
  const updateMenu = (index: number, patch: Partial<MenuItem>) => setMenus((value) => value.map((item, at) => at === index ? { ...item, ...patch } : item));
  return <ConfigShell eyebrow="RESOURCE / PERMISSION CONFIG" title="Authorization matrix" description="Permissions are stored as resource + action. Menu mapping remains presentation-only." dirty={dirty} onSave={() => onCommit((blueprint) => ({ ...blueprint, resources, roles, menus }))} onDiscard={() => { setResources(structuredClone(session.blueprint.resources)); setRoles(structuredClone(session.blueprint.roles)); setMenus(structuredClone(session.blueprint.menus)); }}>
    <div className="permission-guided"><section><span className="step-number">1</span><div><b>Add a resource</b><small>Start with an Entity Config you have already added.</small></div><select aria-label="Entity resource" value={entityResourceKey} onChange={(event) => setEntityResourceKey(event.target.value)} disabled={!availableEntityResources.length}><option value="">{availableEntityResources.length ? "Choose an entity" : "All entities are already resources"}</option>{availableEntityResources.map((entity) => <option value={entity.key} key={entity.key}>{entity.label} ({entity.key})</option>)}</select><button disabled={!availableEntityResources.length} onClick={addEntityResource}>Add selected entity</button></section><section><span className="step-number">2</span><div><b>Choose a role</b><small>Configure permissions for a role that already exists.</small></div><select aria-label="Role to configure" value={selectedRoleKey} onChange={(event) => setSelectedRoleKey(event.target.value)} disabled={!Object.keys(roles).length}><option value="">No role available</option>{Object.entries(roles).map(([key, role]) => <option value={key} key={role.id}>{role.label} ({key})</option>)}</select></section><section><span className="step-number">3</span><div><b>Grant access</b><small>Select a resource, then choose the actions the role needs.</small></div><select aria-label="Grant resource" value={grantResourceId} onChange={(event) => setGrantResourceId(event.target.value)} disabled={!selectedRole || !resourceList.length}><option value="">Choose a resource</option>{resourceList.map((resource) => <option value={resource.id} key={resource.id}>{resource.key}</option>)}</select>{grantResource && <button className="secondary" onClick={() => selectedRole && toggleAll(selectedRoleKey, grantResource)}>{grantResource.actions.every((action) => (selectedRole?.permissions[grantResource.id] ?? []).includes(action)) ? "Clear all" : "Grant all"}</button>}</section></div>
    {selectedRole && <section className="permission-focus"><div className="panel-title"><span>Access for {selectedRole.label}</span><small>{grantResource?.key ?? "choose a resource"}</small></div>{grantResource ? <div className="permission-action-list">{grantResource.actions.map((action) => <label key={action} className={(selectedRole.permissions[grantResource.id] ?? []).includes(action) ? "selected" : ""}><input type="checkbox" aria-label={`${selectedRole.key} ${grantResource.key} ${action}`} checked={(selectedRole.permissions[grantResource.id] ?? []).includes(action)} onChange={() => toggle(selectedRoleKey, grantResource, action)} /><span>{action}</span><small>{action === "read" ? "View records" : action === "create" ? "Add records" : action === "update" ? "Edit records" : action === "delete" ? "Delete records" : "Custom action"}</small></label>)}</div> : <div className="empty-state compact"><strong>Select a resource</strong><span>Its available actions will appear here.</span></div>}</section>}
    <div className="permission-inventory"><section><div className="panel-title"><span>Resources</span><small>{Object.keys(resources).length}</small></div>{Object.entries(resources).map(([key, resource]) => <div className="inventory-row" key={resource.id}><b>{resource.key}</b><span>{resource.actions.map((action) => <button aria-label={`Remove ${resource.key} ${action} action`} onClick={() => removeAction(resource.id, action)} key={action}>{action} ×</button>)}</span><button className="danger" aria-label={`Remove resource ${resource.key}`} onClick={() => removeResource(key, resource.id)}>Remove</button></div>)}</section><section><div className="panel-title"><span>Roles</span><small>{Object.keys(roles).length}</small></div>{Object.entries(roles).map(([key, role]) => <div className="inventory-row" key={role.id}><input aria-label={`${role.key} role label`} value={role.label} onChange={(event) => setRoles((value) => ({ ...value, [key]: { ...role, label: event.target.value } }))} /><button className="danger" aria-label={`Remove role ${role.key}`} onClick={() => setRoles((value) => { const next = { ...value }; delete next[key]; return next; })}>Remove</button></div>)}</section></div>
    <div className="matrix-wrap"><table className="permission-matrix"><thead><tr><th>Role</th>{Object.values(resources).flatMap((resource) => resource.actions.map((action) => <th key={`${resource.id}-${action}`}><span>{resource.key}</span>{action}</th>))}</tr></thead><tbody>{Object.entries(roles).map(([key, role]) => <tr key={role.id}><th>{role.label}</th>{Object.values(resources).flatMap((resource) => resource.actions.map((action) => <td key={`${resource.id}-${action}`}><input type="checkbox" aria-label={`${role.key} ${resource.key} ${action}`} checked={(role.permissions[resource.id] ?? []).includes(action)} onChange={() => toggle(key, resource, action)} /></td>))}</tr>)}</tbody></table></div>
    <section className="menu-config"><div className="panel-title"><span>Menu mapping</span><small>not authorization</small></div><button className="secondary" onClick={() => { const resource = Object.values(resources)[0]; setMenus((value) => [...value, { id: uuid(), label: resource?.key ?? "Menu item", resourceId: resource?.id, order: value.length }]); }}>Add menu item</button>{menus.map((menu, index) => <div className="menu-row advanced" key={menu.id}><input aria-label={`Menu ${index + 1} label`} value={menu.label} onChange={(event) => updateMenu(index, { label: event.target.value })} /><select aria-label={`Menu ${index + 1} resource`} value={menu.resourceId ?? ""} onChange={(event) => updateMenu(index, { resourceId: event.target.value || undefined })}><option value="">No resource</option>{Object.values(resources).map((resource) => <option value={resource.id} key={resource.id}>{resource.key}</option>)}</select><select aria-label={`Menu ${index + 1} parent`} value={menu.parentId ?? ""} onChange={(event) => updateMenu(index, { parentId: event.target.value || undefined })}><option value="">Top level</option>{menus.filter((candidate) => candidate.id !== menu.id).map((candidate) => <option value={candidate.id} key={candidate.id}>{candidate.label}</option>)}</select><input aria-label={`Menu ${index + 1} order`} type="number" value={menu.order} onChange={(event) => updateMenu(index, { order: Number(event.target.value) })} /><button className="danger" aria-label={`Remove menu ${index + 1}`} onClick={() => setMenus((value) => value.filter((_, at) => at !== index).map((item) => item.parentId === menu.id ? { ...item, parentId: undefined } : item))}>Remove</button></div>)}</section>
  </ConfigShell>;
}

export function AuthEditor({ session, onCommit }: { session: ProjectSession; onCommit: Commit }) {
  const entities = Object.values(session.blueprint.entities);
  const [draft, setDraft] = useState<AuthConfig | undefined>(() => structuredClone(session.blueprint.auth));
  const entity = entities.find((item) => item.id === draft?.userEntityId) ?? entities[0];
  const fields = entity ? Object.values(entity.fields) : [];
  const dirty = JSON.stringify(draft) !== JSON.stringify(session.blueprint.auth);
  const enable = () => { if (!entity || !fields[0]) return; setDraft({ databaseId: session.blueprint.databases.main.id, userEntityId: entity.id, externalIdFieldId: fields[0].id, identifierFieldId: fields[0].id, passwordFieldId: fields[0].id, registrationPolicy: "disabled", passwordLogin: true }); };
  const fieldSelect = (label: string, property: "externalIdFieldId" | "identifierFieldId" | "passwordFieldId") => draft && <label>{label}<select value={draft[property]} onChange={(event) => setDraft({ ...draft, [property]: event.target.value })}>{Object.entries(entity?.fields ?? {}).map(([key, field]) => <option value={field.id} key={field.id}>{key}</option>)}</select></label>;
  return <ConfigShell eyebrow="AUTH CONFIGURATION" title="Identity binding" description="Bind authentication to one canonical entity and explicit identity fields." dirty={dirty} onSave={() => onCommit((blueprint) => ({ ...blueprint, auth: draft }))} onDiscard={() => setDraft(structuredClone(session.blueprint.auth))}>
    {!draft ? <div className="empty-large compact"><h2>Authentication is disabled</h2><p>Create an Entity Config first, then enable explicit identity bindings.</p><button className="primary" disabled={!entities.length} onClick={enable}>Enable authentication</button></div> : <div className="auth-form"><label>User entity<select value={draft.userEntityId} onChange={(event) => { const next = entities.find((item) => item.id === event.target.value); const first = Object.values(next?.fields ?? {})[0]; if (next && first) setDraft({ ...draft, userEntityId: next.id, externalIdFieldId: first.id, identifierFieldId: first.id, passwordFieldId: first.id }); }}>{entities.map((item) => <option value={item.id} key={item.id}>{item.label ?? item.id}</option>)}</select></label>{fieldSelect("External identity field", "externalIdFieldId")}{fieldSelect("Login identifier field", "identifierFieldId")}{fieldSelect("Password hash field", "passwordFieldId")}<label>Registration policy<select value={draft.registrationPolicy} onChange={(event) => setDraft({ ...draft, registrationPolicy: event.target.value as AuthConfig["registrationPolicy"] })}><option value="disabled">Disabled</option><option value="inviteOnly">Invite only</option><option value="open">Open</option></select></label><label className="check"><input type="checkbox" checked={draft.passwordLogin} onChange={(event) => setDraft({ ...draft, passwordLogin: event.target.checked })} /> Enable password login</label><button className="secondary danger" onClick={() => setDraft(undefined)}>Disable authentication</button></div>}
  </ConfigShell>;
}

export function GlobalEditor({ session, onCommit }: { session: ProjectSession; onCommit: Commit }) {
  const [template] = useState(session.blueprint.global.template || "default");
  const [settings, setSettings] = useState(() => JSON.stringify(session.blueprint.global.settings, null, 2));
  const [error, setError] = useState<string | null>(null);
  const dirty = settings !== JSON.stringify(session.blueprint.global.settings, null, 2);
  const save = () => { try { const value = JSON.parse(settings) as Record<string, unknown>; setError(null); onCommit((blueprint) => ({ ...blueprint, global: { template, settings: value } })); } catch { setError("Settings must be a valid JSON object"); } };
  return <ConfigShell eyebrow="GLOBAL CONFIG" title="Template settings" description="Configure template inputs. Template overrides remain outside the MVP." dirty={dirty} onSave={save} onDiscard={() => { setSettings(JSON.stringify(session.blueprint.global.settings, null, 2)); setError(null); }}><div className="global-form"><label>Template<input value={template} readOnly /></label><label>Settings JSON<textarea value={settings} onChange={(event) => setSettings(event.target.value)} spellCheck={false} /></label>{error && <p className="form-error">{error}</p>}</div></ConfigShell>;
}

function FieldAdvanced({ field, entities, onChange }: { field: EntityFieldConfig; entities: Record<string, EntityConfig>; onChange: (patch: Partial<EntityFieldConfig>) => void }) {
  const rule = (kind: string) => field.validation.find((item) => item.kind === kind)?.value ?? "";
  const setRule = (kind: string, value: string) => {
    const validation = field.validation.filter((item) => item.kind !== kind);
    if (value.trim()) validation.push({ kind, value: kind === "minLength" || kind === "maxLength" ? Number(value) : value });
    onChange({ validation });
  };
  const target = Object.values(entities).find((entity) => entity.id === field.relationDisplay?.targetEntityId);
  return <section className="field-advanced">
    <div className="panel-title"><span>Selected field rules</span><small>validation / options / relation</small></div>
    <div className="advanced-grid"><label>Minimum length<input type="number" min="0" value={String(rule("minLength"))} onChange={(event) => setRule("minLength", event.target.value)} /></label><label>Maximum length<input type="number" min="0" value={String(rule("maxLength"))} onChange={(event) => setRule("maxLength", event.target.value)} /></label><label>Pattern<input value={String(rule("pattern"))} placeholder="^[a-z]+$" onChange={(event) => setRule("pattern", event.target.value)} /></label></div>
    <label>Static options <small>one option per line: Label=value</small><textarea value={field.options.map((option) => `${option.label}=${option.value}`).join("\n")} onChange={(event) => onChange({ options: event.target.value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [label, ...rest] = line.split("="); return { label: label.trim(), value: (rest.join("=") || label).trim() }; }) })} /></label>
    <div className="advanced-grid"><label>Relation entity<select value={field.relationDisplay?.targetEntityId ?? ""} onChange={(event) => { const next = Object.values(entities).find((entity) => entity.id === event.target.value); const first = Object.values(next?.fields ?? {})[0]; onChange({ relationDisplay: next && first ? { targetEntityId: next.id, displayFieldId: first.id, missingBehavior: "rawValue" } : undefined }); }}><option value="">No relation display</option>{Object.entries(entities).map(([key, entity]) => <option value={entity.id} key={entity.id}>{entity.label ?? key}</option>)}</select></label><label>Display field<select disabled={!target} value={field.relationDisplay?.displayFieldId ?? ""} onChange={(event) => field.relationDisplay && onChange({ relationDisplay: { ...field.relationDisplay, displayFieldId: event.target.value } })}>{Object.entries(target?.fields ?? {}).map(([key, item]) => <option value={item.id} key={item.id}>{key}</option>)}</select></label><label>Missing relation<select disabled={!field.relationDisplay} value={field.relationDisplay?.missingBehavior ?? "rawValue"} onChange={(event) => field.relationDisplay && onChange({ relationDisplay: { ...field.relationDisplay, missingBehavior: event.target.value as "empty" | "rawValue" | "error" } })}><option value="empty">Empty</option><option value="rawValue">Raw value</option><option value="error">Error</option></select></label></div>
  </section>;
}

function ConfigShell({ eyebrow, title, description, dirty, onSave, onDiscard, children }: { eyebrow: string; title: string; description: string; dirty: boolean; onSave: () => void; onDiscard: () => void; children: React.ReactNode }) {
  return <div className="page config-page"><div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="editor-actions"><span className={dirty ? "draft-indicator dirty" : "draft-indicator"}>{dirty ? "Unsaved draft" : "No changes"}</span><button className="secondary" disabled={!dirty} onClick={onDiscard}>Discard</button><button className="primary" disabled={!dirty} onClick={onSave}>Apply config</button></div></div><section className="panel config-workspace">{children}</section></div>;
}

function EmptyConfig({ text }: { text: string }) { return <div className="empty-state"><strong>No configuration</strong><span>{text}</span></div>; }
